# Generated by Django 4.2.1 on 2024-05-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_node_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
