# Generated by Django 4.2.1 on 2024-05-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_node_ip_address_alter_node_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='node_id',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
