version: '3'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: debug
    ports:
      - 5432:5432
  web:
    restart: always
    environment:
      - DJANGO_SECRET_KEY=local
      - DJANGO_SECRET_KEY=ez=gtk3q1_qtzta64&ejc7@!@l+y@n+8%(tq=xi+x@ccipoa^@
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USERNAME=postgres
      - POSTGRES_PASSWORD=debug
      - POSTGRES=postgres
      - DJANGO_CONFIGURATION=Local
      - API_KEY_SECRET=ada3da3d
    build: ./
    entrypoint: ash
    command: ./start.sh
    ports:
      - "8004:8000"
    depends_on:
      - postgres
      - redis
  documentation:
    restart: always
    build: ./
    command: "mkdocs serve"
    ports:
      - "8001:8001"
  # command: redis-server --requirepass redis & celery
  redis:
    image: redis:alpine
  celery-beat:
    build: ./
    command: celery -A delusion beat --loglevel=info
    environment:
      - DJANGO_SECRET_KEY=local
      - DJANGO_SECRET_KEY=ez=gtk3q1_qtzta64&ejc7@!@l+y@n+8%(tq=xi+x@ccipoa^@
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USERNAME=postgres
      - POSTGRES_PASSWORD=debug
      - POSTGRES=postgres
      - DJANGO_CONFIGURATION=Local
      - API_KEY_SECRET=ada3da3d
    depends_on:
      - redis
    
  celery:
    build: ./
    command: celery -A delusion worker -l info
    environment:
      - DJANGO_SECRET_KEY=local
      - DJANGO_SECRET_KEY=ez=gtk3q1_qtzta64&ejc7@!@l+y@n+8%(tq=xi+x@ccipoa^@
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USERNAME=postgres
      - POSTGRES_PASSWORD=debug
      - POSTGRES=postgres
      - DJANGO_CONFIGURATION=Local
      - API_KEY_SECRET=ada3da3d
    depends_on:
      - redis



  # pgadmin:
  #   container_name: pgadmin4_container
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   ports:
  #     - "5050:80"

  