# Generated by Django 4.2.1 on 2023-09-15 17:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import delusion.company.validators


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/ticket/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'png', 'jpeg', 'txt', 'log']), delusion.company.validators.validate_file_mimetype])),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_files', to='company.ticket', verbose_name='ticket')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MessageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/ticket/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'png', 'jpeg', 'txt', 'log']), delusion.company.validators.validate_file_mimetype])),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_files', to='company.message', verbose_name='message')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
