# Generated by Django 4.2.1 on 2023-10-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0002_cpu_gpu_pcuser_node_antivirus_node_auto_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='pc_users',
            field=models.ManyToManyField(blank=True, related_name='nodes', to='node.pcuser'),
        ),
    ]
