# Generated by Django 4.2.1 on 2023-10-20 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0004_alter_node_antivirus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='antivirus',
            field=models.CharField(blank=True, choices=[('l', 'Low'), ('m', 'Medium'), ('h', 'High')], max_length=2, null=True),
        ),
    ]
