name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH
      run: sudo apt-get install openssh-client -y

    - name: Deploy to Ubuntu Server
      env:
        SERVER_ADDRESS: ${{ secrets.SERVER_ADDRESS }}
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        sshpass -p $PASSWORD ssh $USERNAME@$SERVER_ADDRESS "echo 'Connected successfully!'"
